# Image Rotation

In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("C:/Users/SN61/Music/th (1).jpg")

In [3]:
im1

array([[[201, 188, 120],
        [179, 167,  97],
        [164, 154,  77],
        ...,
        [247, 202, 121],
        [250, 204, 127],
        [251, 205, 128]],

       [[207, 193, 127],
        [187, 174, 106],
        [169, 158,  84],
        ...,
        [242, 199, 120],
        [246, 202, 125],
        [248, 204, 127]],

       [[234, 216, 155],
        [218, 201, 138],
        [195, 179, 112],
        ...,
        [241, 200, 121],
        [243, 201, 124],
        [244, 202, 127]],

       ...,

       [[ 56,  93,  53],
        [ 56,  96,  55],
        [ 57,  97,  56],
        ...,
        [ 56,  50,  37],
        [ 56,  50,  37],
        [ 64,  58,  45]],

       [[ 55,  92,  52],
        [ 57,  94,  54],
        [ 56,  96,  55],
        ...,
        [ 53,  47,  34],
        [ 57,  51,  40],
        [ 72,  66,  55]],

       [[ 53,  90,  50],
        [ 55,  92,  52],
        [ 54,  94,  53],
        ...,
        [ 50,  44,  31],
        [ 59,  53,  42],
        [ 80,  74,  63]]

In [4]:
shp=im1.shape

In [5]:
print(shp)

(243, 432, 3)


In [6]:
height,width=im1.shape[:2]
print(height)
print(width)

243
432


In [7]:
cntr=(height/2,width/2)

In [8]:
cntr

(121.5, 216.0)

In [9]:
rotation_matrix=cv2.getRotationMatrix2D(center=cntr,angle=30,scale=0.5)

In [10]:
print(rotation_matrix)

[[  0.4330127    0.25        14.88895672]
 [ -0.25         0.4330127  152.84425639]]


In [11]:
rotated_im=cv2.warpAffine(src=im1, M=rotation_matrix, dsize=(width,height))

In [ ]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('rotated image',rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Translation matrix

In [ ]:
tx,ty=width/2,height/2

In [ ]:
tx

In [ ]:
ty

In [ ]:
Translation_matrix=np.array([[3,0,tx],[0,2,ty]])

In [ ]:
Translation_matrix

In [ ]:
Trans_im=cv2.warpAffine(src=im1, M=Translation_matrix, dsize=(width,height))

In [ ]:
cv2.imshow('original image',im1)
cv2.waitKey(0)
cv2.imshow('Trans image',Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()