# IMAGE SEGMENTATION IN K-MEANS

In [3]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("C:/Users/SN61/Downloads/desktop-wallpaper-cute-panda-iphone-cute-panda-love-thumbnail.jpg",0)

In [3]:
img

array([[164, 166, 167, ..., 167, 168, 163],
       [164, 166, 167, ..., 173, 171, 169],
       [163, 165, 166, ..., 176, 172, 172],
       ...,
       [163, 161, 163, ..., 158, 160, 158],
       [165, 162, 162, ..., 157, 158, 156],
       [168, 164, 163, ..., 156, 157, 154]], dtype=uint8)

# RGB Conversion

In [5]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# Reshape

In [6]:
vec=imgrgb.reshape((-1,3))

In [7]:
vec

array([[164, 164, 164],
       [166, 166, 166],
       [167, 167, 167],
       ...,
       [156, 156, 156],
       [157, 157, 157],
       [154, 154, 154]], dtype=uint8)

# Float Conversion

In [8]:
vec=np.float32(vec)

In [9]:
vec

array([[164., 164., 164.],
       [166., 166., 166.],
       [167., 167., 167.],
       ...,
       [156., 156., 156.],
       [157., 157., 157.],
       [154., 154., 154.]], dtype=float32)

# Iterartion Termination Criteria

In [11]:
Criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

# Cluster Condition

In [12]:
k=2
attempts=100

# K-Means Clustering

In [16]:
compactness,label,center=cv2.kmeans(vec,k,None,Criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [17]:
center

array([[ 40.75893,  40.75893,  40.75893],
       [209.63466, 209.63466, 209.63466]], dtype=float32)

# Unit Conversion

In [27]:
center=np.uint8(center)

In [28]:
center

array([[ 40,  40,  40],
       [209, 209, 209]], dtype=uint8)

In [29]:
label=np.uint8(label)

In [30]:
label

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=uint8)

In [32]:
copmpactness=np.uint8(compactness)

In [33]:
compactness

815736808.1511163

# Flattening and Reshape

In [34]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))

In [35]:
res_img

array([[[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]],

       ...,

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]],

       [[209, 209, 209],
        [209, 209, 209],
        [209, 209, 209],
        ...,
        [209, 209, 209],
        [209, 209, 209],
        [209, 209, 209]]

# Original and Segmented image

In [39]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
img=cv2.imread("C:/Users/SN61/Downloads/images (1).jfif")

In [9]:
segmented_img=cv2.pyrMeanShiftFiltering(img,10,50)

In [ ]:
cv2.imshow('original_img',img)
cv2.imshow('segmented_img',segmented_img)
cv2.waitKey(0)
cv2.destroyAllWindows()